### ISSUE TITLE
[Bug]added url shows error 

### ISSUE THREAD

**Issue by codewithshubhi** [storybookjs/frontpage#396] opened 2022-10-07 19:12 UTC
### Describe the bug

The documentation pages end up with a unnecessary #gatsby-focus-wrapper anchor in the url

### Steps to reproduce the behavior

1. Go to https://app.netlify.com/sites/storybook-frontpage/settings/deploys#environment
2. See error

### Expected behavior

Should be able to view the webpage and navigate using route.

### Screenshots and/or logs

![image](https://user-images.githubusercontent.com/70970530/194637060-d280c56e-a34a-4d53-91ce-a0bcf77bdf55.png)

**Comment by aditi824** [comment] 2022-10-08 14:17
I want to contribute to this issue.

**Comment by winkerVSbecks** [comment] 2022-10-08 17:20
duplicate of #284

**Closed by winkerVSbecks** 2022-10-08 17:20 UTC
Labels: bug
