### ISSUE TITLE
[Bug] When you open two web pages for comparison, only one frame can be selected.

### ISSUE THREAD

**Issue by zhanghengxin** [storybookjs/frontpage#693] opened 2024-05-11 08:36 UTC
### Steps to reproduce the behavior

open they:
https://storybook.js.org/docs/get-started/web-components-vite
https://storybook.js.org/docs/get-started/vue3-vite

I cant comparing.

### Screenshots and/or logs

If applicable, add screenshots and/or logs to help explain your problem.

### Environment

 - Node.js version: [e.g. v12.17.0]
 - NPM version: [e.g. 6.14.4]
 - Browser (if applicable): [e.g. chrome, safari]
 - Browser version (if applicable): [e.g. 22]
 - Device (if applicable): [e.g. iPhone6]

### Additional context

Move the sb-docs-selected-framework to sessionStorage.

**Comment by kylegach** [comment] 2024-06-06 15:29
This is by design. The docs site should remember which renderer is selected. Moving it into session storage would only save for the session, so starting a new session would reset it back to the default, `react`.

If you wish to compare docs for multiple renderers, please use a private/incognito window or different browsers.

**Closed** 2024-06-06 15:29 UTC
Labels: bug
