### ISSUE TITLE
Wrong Readme for Addons on storybook.js.org

### ISSUE THREAD

**Issue by doublejosh** [storybookjs/frontpage#233] opened 2021-02-25 00:57 UTC
Addon pages show the root Storybook readme file rather than the readme for the addon.

**To Reproduce**
Addon pages like these...
https://storybook.js.org/addons/@storybook/addon-knobs
https://storybook.js.org/addons/@storybook/addon-queryparams

**Expected behavior**
Should show the readme file like these...
https://github.com/storybookjs/storybook/tree/next/addons/knobs
https://github.com/storybookjs/storybook/tree/next/addons/queryparams

**Comment by domyen** [comment] 2021-02-25 15:54
@shilman the frontend (i.e., /frontpage) gets these readme URLs from the addon catalog backend?

**Comment by winkerVSbecks** [comment] 2021-06-28 15:08
duplicate of #263

**Closed by winkerVSbecks** 2021-06-28 15:08 UTC
